QUOTES = [
    "a mente é tudo. o que você pensa, você se torna.",
    "a paz vem de dentro. não a procure fora.",
    "três coisas não podem ficar ocultas por muito tempo: o sol, a lua e a verdade.",
    "não há caminho para a felicidade. a felicidade é o caminho.",
    "o sofrimento é necessário até que você perceba que ele é desnecessário.",
    "o que você é, é o que você foi. o que você será é o que você faz agora.",
    "aquele que olha para fora sonha; aquele que olha para dentro desperta.",
    "a única forma de fazer um bom trabalho é amar o que você faz.",
    "faça de cada momento uma razão para se abrir.",
    "o presente nunca será o que foi. cada instante é novo.",
    "quando você percebe que não há nada faltando, o mundo inteiro pertence a você.",
    "a vida é uma série de mudanças naturais e espontâneas. não resista a elas.",
    "conhecer os outros é sabedoria. conhecer a si mesmo é iluminação.",
    "agir sem expectativas, liderar sem querer controlar.",
    "aquele que sabe não fala. aquele que fala não sabe.",
    "o silêncio é uma fonte de grande força.",
    "ser profundamente amado por alguém nos dá força; amar alguém profundamente nos dá coragem.",
    "da mesma forma que a vela não pode arder sem fogo, o homem não pode viver sem uma vida espiritual.",
    "se você iluminar o caminho de outro, você também verá melhor.",
    "o homem que se move uma montanha começa carregando pequenas pedras.",
    "quando as intenções são puras, o coração está em paz.",
    "o verdadeiro mestre é aquele que aponta para além de si mesmo.",
    "viver de forma simples para que outros possam simplesmente viver.",
    "a jornada de mil milhas começa com um único passo.",
    "a vida não é medida pelo número de respirações que tomamos, mas pelos momentos que nos tiram o fôlego.",
    "toda manhã somos nascidos de novo. o que fazemos hoje é o que mais importa.",
    "se você está tranquilo, você é tranquilo em qualquer lugar.",
    "a raiz do sofrimento é o apego.",
    "na natureza não há nada desperdiçado.",
    "o sábio não se preocupa com o passado nem anseia pelo futuro. ele vive o presente.",
    "cada momento é eterno.",
    "deixe ir. como tudo dentro de você, deixe que as coisas venham e vão.",
    "o verdadeiro amor é saber como dar espaço à outra pessoa.",
    "quando chover, deixe chover.",
    "o vazio é a condição para que tudo possa surgir.",
    "não existe nada permanente exceto a mudança.",
    "a bondade em palavras cria confiança. a bondade em pensamentos cria profundidade. a bondade em dar cria amor.",
    "a mente tranquila é mais valiosa do que qualquer tesouro externo.",
    "quando você percebe que há grandeza em cada coisa simples, você é abençoado.",
    "nada nunca vai embora até que nos ensine o que precisamos saber.",
    "a flor que desabrocha na adversidade é a mais rara e bela de todas.",
    "seja como a água: suave o suficiente para dar vida, forte o suficiente para esculpir pedras.",
    "a mente do iniciante está aberta, cheia de possibilidades. a mente do especialista tem poucas.",
    "tudo que você procura está dentro de você.",
    "o vento não quebra uma árvore que sabe como dobrar.",
    "não é o que você olha que importa, é o que você vê.",
    "um espelho sujo não pode refletir a luz claramente.",
    "fique quieto. o segredo do mundo está em sua própria quietude.",
    "cada respiração é um novo começo.",
    "antes de iluminar, cortar lenha e carregar água. depois de iluminar, cortar lenha e carregar água.",
    "a lua não sente falta de si mesma quando sua imagem some da água.",
    "não tente mover o mundo. comece por dar um único passo.",
    "a forma que você vê as pessoas é a forma que você as trata, e a forma que as trata é quem você é.",
    "a mente é um jardim. os pensamentos são as sementes. você pode cultivar flores ou deixar crescer ervas daninhas.",
    "a verdadeira riqueza é contar com o suficiente.",
    "quem é sábio não discute; quem discute não é sábio.",
    "o coração que dá é sempre cheio.",
    "não force nada. o que flui virá; o que vai, vai.",
    "cada pedra no caminho é parte do caminho.",
    "a virtude não é inatividade. é agir com integridade em cada momento.",
    "quando estamos perdidos, a quietude nos encontra.",
    "o tempo que você aprecia gastar não é tempo desperdiçado.",
    "ensine suas crianças com menos palavras e mais silêncio.",
    "a bondade é uma linguagem que surdos podem ouvir e cegos podem ver.",
    "aquele que não tem paz interior vai procurá-la em vão em outro lugar.",
    "a vida é simples, mas insistimos em torná-la complicada.",
    "o momento presente sempre terá sido.",
    "o que resiste, persiste. o que aceitas, transforma.",
    "quando o bambú está vazio por dentro, o vento pode cantar através dele.",
    "a compaixão não tem limites. a bondade não tem fronteiras.",
    "observe seus pensamentos: eles se tornam palavras. observe suas palavras: elas se tornam ações.",
    "onde a mente vai, a energia flui.",
    "a gentileza deve ser a respiração do dia a dia.",
]
